#!/bin/sh

# +--------------------------------------------+
# | XORG CONFIG FILE ---by-Sebastian-Dorobantu |
# +--------------------------------------------+

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi




# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.config/X11/.Xresources ]] && xrdb -merge -I$HOME ~/.config/X11/.Xresources

xrandr --output DVI-D-0 --off --output HDMI-1 --mode 1920x1080 --pos 2368x280 --rotate normal --output HDMI-0 --same-as HDMI-1 --output DP-0 --mode 1360x768 --pos 1600x0 --rotate right --output DP-1 --off --output DP-2 --mode 1600x900 --pos 0x230 --rotate normal --output DP-3 --off
autokey-gtk &
picom &
megasync &
xset -dpms & # Disables Energy Star features
xset s off & # Disables screen saver
nitrogen --restore &


exec qtile start

